### ISSUE TITLE
Trying to add project in cmake

### ISSUE THREAD

**Issue by svb688** [guitargeek/XGBoost-FastForest#6]
I am trying to add this project to my existing project.
As per [cmake](https://cmake.org/cmake/help/v3.17/module/FetchContent.html) I have the following:
```
include(FetchContent)
FetchContent_Declare(
  XGBoost-FastForest
  GIT_REPOSITORY https://github.com/guitargeek/XGBoost-FastForest
)
FetchContent_MakeAvailable(XGBoost-FastForest)
```

However, when I try to compile I am having issues with including the main header file `fastforest.h`.

**Comment by guitargeek** [comment]
Hi @svb688, can you be more specific about the issue you encounter? I tried to reproduce it by:

1. taking a minimal cmake example (https://github.com/krux02/minimal_cmake_example)
2. adding your snipped to the `CMakeLists.txt`
3. adding `fastforest` to the list of linked libraries in the `target_link_libraries` part
4. include `fastforest.h` in the projects `main.cpp`:
    ````C++
    #include "fastforest.h"
    ````
5. Calling some fastforest functionality in `MAIN()` to see if it gets correctly linked:
    ````C++
    std::vector<std::string> features{"f0", "f1", "f2", "f3", "f4"};
    const auto fastForest = fastforest::load_txt("model.txt", features);
    ````

Since this compiles flawlessly, I don't see at the moment how this is a fastforest issue. Maybe you have tried to include it as `<fastforest.h>`, but it should be in double quotes? Or you forgot to link it? Maybe the minimal example I referenced above can help you  to solve your problem.

 [1], added your snippet to the CMakeLists.txt and

**Comment by svb688** [comment]
OK Must be something on my end. I am having issues recreating your example as well.

src/main/main.cpp
```
#include "main.h"
#include "fastforest.h"
// REST OF main.cpp
```

CMakeLists.txt
```
include(FetchContent)
FetchContent_Declare(
  XGBoost-FastForest
  GIT_REPOSITORY https://github.com/guitargeek/XGBoost-FastForest
)
FetchContent_MakeAvailable(XGBoost-FastForest)

# then below in the dependencies section I have:

target_link_libraries(example PUBLIC
  ${Boost_LIBRARIES}
  fastforest
  # here you can add any library dependencies
)
```

Yet when I try to make
````
minimal_cmake_example/src/main/main.cpp:13:10: fatal error: fastforest.h: No such file or directory
   13 | #include "fastforest.h"
```


If you're able to assist or send your implementation that would be great, Since you're able to make it work the issue seems to be on my end, so you're welcome to close the issue and I can report back later if I figure out what's going on.

**Comment by svb688** [comment]
also, what version of cmake are you using? I am using 3.14.5

**Comment by guitargeek** [comment]
I am using cmake version 3.17.3, so maybe it's a cmake version issue.

Have you tried setting the include directory explicitly for the target? Like this, in our minimal example.
Note that I changed the content name from `XGBoost-FastForest` to simply `fastforest`, because upper case and the dash caused trouble with the `*_SOURCE_DIR` variable.
```
include(FetchContent)
FetchContent_Declare(
  fastforest
  GIT_REPOSITORY https://github.com/guitargeek/XGBoost-FastForest
)
FetchContent_MakeAvailable(fastforest)

target_link_libraries(example PUBLIC
  ${Boost_LIBRARIES}
  fastforest
  # here you can add any library dependencies
)
message( ${fastforest_SOURCE_DIR} ) # this is just a log to see if the include dir is correct
target_include_directories(example PUBLIC ${fastforest_SOURCE_DIR}/include)
```

I got inspired a bit by this issue here:
https://github.com/Skycoder42/QHotkey/issues/24

**Comment by svb688** [comment]
ah ha! it did end up being the dash. Thanks for your help. First time using FetchContent!

**Comment by guitargeek** [comment]
You are welcome! I didn't know about FetchContent before and was happy to learn about this nice CMake feature.
